
#if 1

//Assignment 04 question #2
//The goal of the assignment is to create two functions: func1 and func2
//func2 calls func1 within 
//See what is is the assembly code generated by compiler and how the arguments are
//passed from func2 to func1


//prototype for func1 and func2
int func1(int a, int b, int c, int e, int f); 
int fun2(); 

int m = 10;
int n = 11;
int s = 12;
int t = 13;
int u = 14;
float average;
int sum;

int main(){

    func2(); // calculates average
    
    return 0;
}

//func1 returns the sum five input arguments
int func1(int v , int w, int x, int y, int z){
    sum = (u + v + w + x +y); 
    return sum; 
}

//func2 calls func1 --> and calculates average of the five numbers
int func2(){
   average = func1(m, n , s, t, u)/5; // call func1 to add five numbers of int type
   return average;
}
#endif